### ISSUE TITLE
P+ criterion 6: Argue critically about the benefits, drawbacks, etc.

### ISSUE THREAD

**Issue by gustafssonlinnea** [DD2480G19/teammates2#18]
P+ criterion 6: You can argue critically about the benefits, drawbacks, and limitations of your work carried out, in the context of current software engineering practice, such as the SEMAT kernel (covering alphas other than Team/Way of Working).

**Comment by markusnewtonh** [comment]
Draft (before work is done) is complete.
[Gdoc](https://docs.google.com/document/d/1HBsuYGFRaxV56TDoFMI-g9P7bpmYuK7dLm1836pjub4/edit?usp=sharing)
