### ISSUE TITLE
`execute`: If existing responses for recipient, responses are updated (ex08)

### ISSUE THREAD

**Issue by markusnewtonh** [DD2480G19/teammates2#37]
**Edit: This is not valid anymore, see comment below.**

Test two (2) cases:

1. If there are existing responses for the recipient, the responses should be updated.
2. If there are no existing responses for the recipient, the responses should not be updated.

**Comment by FalkWasTaken** [comment]
Changed the issue to better fit with the updated requirements. New requirement:
>If there are existing responses for a recipient, the responses should be updated and reflected in the JSON result/database.
