### ISSUE TITLE
Test: `execute`: update database if submission request includes responses

### ISSUE THREAD

**Issue by markusnewtonh** [DD2480G19/teammates2#38]
Test two (2) cases:

1. If there are no responses in the submission request (`submitRequest.getResponses()`), no changes should be made to the database. 
2. If there are responses in the submission request (`submitRequest.getResponses()`), the database should be updated.

**Comment by FalkWasTaken** [comment]
This requirement is probably wrong and we have updated the docs accordingly. Should we refactor this issue or create new ones?
